bulk: bulk::provider::BulkTranslator Class Reference
bulk::provider::BulkTranslator Class Reference
#include "bulk_translator.hpp"
Classes
struct State
Public Types
using Subscriber = SubscriberBase< BulkEvent >
using WPtrSubscriber = std::weak_ptr< Subscriber >
using SPtrSubscriber = std::shared_ptr< Subscriber >
using VPtrSubscriber = std::variant< WPtrSubscriber, SPtrSubscriber >
Public Member Functions
core::SubscriptionStatus getSubscriptionStatus () noexcept override
Get Subscriber current State object.
core::SubscriptionStatus onEvent (cmd::TokenEvent const &event) override
Main Subscription Method.
virtual std::string getSubscriberID () final
Get the Subscriber Id object (internal usage for subsciber identification)
void subscribe (SPtrSubscriber const &subscriber, bool own)
void subscribe (SPtrSubscriber &&subscriber)
bool hasSubscription ()
void unsubscribe (SPtrSubscriber const &subscriber)
void clear ()
Static Public Member Functions
static std::shared_ptr< BulkTranslator > create (size_t BULK_SIZE)
Protected Member Functions
virtual std::string getSubscriberName () const noexcept
Get Subscriber Name (local within derived type)
void notify (BulkEvent const &event)
Private Types
using VState = std::variant< State::Base, State::Block, State::Failed, State::Finish >
Private Member Functions
BulkTranslator (size_t BULK_SIZE)
std::optional< SPtrSubscriber > _getShared (VPtrSubscriber const &vptr)
auto _findSteady (std::string_view id)
void _refresh ()
Private Attributes
const size_t _BULK_SIZE
VState _state
BulkEvent _bulk
std::string _id
std::list< VPtrSubscriber > _subs
Detailed Description
Definition at line 15 of file bulk_translator.hpp.
Class Documentation
bulk::provider::BulkTranslator::State
struct bulk::provider::BulkTranslator::State
Definition at line 106 of file bulk_translator.hpp.
Member Typedef Documentation
SPtrSubscriber
using core::PublisherMixin< BulkEvent >::SPtrSubscriber = std::shared_ptr<Subscriber> inherited
Definition at line 14 of file publisher.hpp.
Subscriber
using core::PublisherMixin< BulkEvent >::Subscriber = SubscriberBase<BulkEvent > inherited
Definition at line 12 of file publisher.hpp.
VPtrSubscriber
using core::PublisherMixin< BulkEvent >::VPtrSubscriber = std::variant<WPtrSubscriber, SPtrSubscriber> inherited
Definition at line 15 of file publisher.hpp.
VState
using bulk::provider::BulkTranslator::VState = std::variant<State::Base, State::Block, State::Failed, State::Finish> private
Definition at line 115 of file bulk_translator.hpp.
WPtrSubscriber
using core::PublisherMixin< BulkEvent >::WPtrSubscriber = std::weak_ptr<Subscriber> inherited
Definition at line 13 of file publisher.hpp.
Constructor & Destructor Documentation
BulkTranslator()
bulk::provider::BulkTranslator::BulkTranslator (size_t BULK_SIZE) inline private
Definition at line 102 of file bulk_translator.hpp.
                                   : _BULK_SIZE{BULK_SIZE}, _state{State::Base{}} {
    _bulk.commands.reserve(_BULK_SIZE);
  }
References _bulk, _BULK_SIZE, and bulk::BulkEvent::commands.
Member Function Documentation
_findSteady()
auto core::PublisherMixin< BulkEvent >::_findSteady (std::string_view id) inline private inherited
Definition at line 86 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        if (spo.value()->getSubscriberID() == id) return it;
        ++it;
      } else {
        it = _subs.erase(it);
      }
    }
    return _subs.end();
  }
_getShared()
std::optional< SPtrSubscriber > core::PublisherMixin< BulkEvent >::_getShared (VPtrSubscriber const & vptr) inline private inherited
Definition at line 76 of file publisher.hpp.
{
    if (std::holds_alternative<WPtrSubscriber>(vptr)) {
      if (auto sp = std::get<WPtrSubscriber>(vptr).lock())
        return sp;
      else
        return std::nullopt;
    }
    return std::get<SPtrSubscriber>(vptr);
  }
_refresh()
void core::PublisherMixin< BulkEvent >::_refresh () inline private inherited
Definition at line 98 of file publisher.hpp.
                  {
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        if (SubscriptionStatus::CANCEL == spo.value()->getSubscriptionStatus())
          it = _subs.erase(it);
        else
          ++it;
      } else {
        it = _subs.erase(it);
      }
    }
  }
clear()
void core::PublisherMixin< BulkEvent >::clear () inline inherited
Definition at line 42 of file publisher.hpp.
{ _subs.clear(); }
create()
static std::shared_ptr< BulkTranslator > bulk::provider::BulkTranslator::create (size_t BULK_SIZE) inline static
Definition at line 19 of file bulk_translator.hpp.
{
    return std::shared_ptr<BulkTranslator>(new BulkTranslator(BULK_SIZE));
  }
Referenced by main().
getSubscriberID()
virtual std::string core::SubscriberBase< cmd::TokenEvent >::getSubscriberID () inline final virtual inherited
Get the Subscriber Id object (internal usage for subsciber identification)
= {typeid(*this).name()}.{this->getSubscriberLocalName()}
Returns
std::string
Definition at line 47 of file subscriber.hpp.
{
    if (_id == "") _id = std::format("{}.{}", typeid(*this).name(), this->getSubscriberName());
    return _id;
  }
getSubscriberName()
virtual std::string core::SubscriberBase< cmd::TokenEvent >::getSubscriberName () const inline protected virtual noexcept inherited
Get Subscriber Name (local within derived type)
applied as a suffix to typeid(*this) to identify subscribers of the same type
Returns
* std::string
Reimplemented in logs::OutputStreamWriter.
Definition at line 61 of file subscriber.hpp.
{ return ""; }
getSubscriptionStatus()
core::SubscriptionStatus bulk::provider::BulkTranslator::getSubscriptionStatus () inline override virtual noexcept
Get Subscriber current State object.
used by publisher before calling onEvent method state management is done in derived classes as needed (see file_writer.hpp)
Returns
SubscriptionStatus
Reimplemented from core::SubscriberBase< cmd::TokenEvent >.
Definition at line 23 of file bulk_translator.hpp.
{
    return (std::holds_alternative<State::Base>(_state) || std::holds_alternative<State::Block>(_state))
               ? core::SubscriptionStatus::READY
               : core::SubscriptionStatus::CANCEL;
  }
References _state, core::CANCEL, and core::READY.
Referenced by onEvent().
hasSubscription()
bool core::PublisherMixin< BulkEvent >::hasSubscription () inline inherited
Definition at line 35 of file publisher.hpp.
{
    _refresh();
    return (_subs.size() > 0);
  }
notify()
void core::PublisherMixin< BulkEvent >::notify (BulkEvent const & event) inline protected inherited
Definition at line 47 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        auto& sp = spo.value();
        switch (sp->getSubscriptionStatus()) {
          case SubscriptionStatus::READY:
            try {
              if (SubscriptionStatus::CANCEL == sp->onEvent(event))
                it = _subs.erase(it);
              else
                ++it;
            } catch (...) {
              it = _subs.erase(it);
            }
            break;
          case SubscriptionStatus::SUSPEND:
            ++it;
            break;
          case SubscriptionStatus::CANCEL:
            it = _subs.erase(it);
            break;
        }
      } else {
        it = _subs.erase(it);
      }
    }
  }
onEvent()
core::SubscriptionStatus bulk::provider::BulkTranslator::onEvent (cmd::TokenEvent const & event) inline override virtual
Main Subscription Method.
if exception is thrown then publisher will unsubscribe this subscriber on its side imediatly but to unsubscribe in normal way it's better just to return 'SubscriptionStatus::CANCEL' status
Parameters
event
Returns
SubscriptionStatus state after handling onEvent method
Implements core::SubscriberBase< cmd::TokenEvent >.
Definition at line 29 of file bulk_translator.hpp.
{
    _state = std::visit(
      utils::overload{
        // Base:
        [&](State::Base & state, cmd::TokenCommand const& tok) -> VState {
          if (_bulk.commands.size() == 0)
            _bulk.time_stamp = std::chrono::system_clock::now();
          _bulk.commands.emplace_back(tok.value);
          if (_bulk.commands.size() >= _BULK_SIZE){
            notify(_bulk);
            _bulk.commands.clear();
          }
          return state;
        },
        [&](State::Base &, cmd::TokenBlockBegin const&) -> VState {
          if (_bulk.commands.size()){
            notify(_bulk);
            _bulk.commands.clear();
          }
          return State::Block{1};
        },
        [&](State::Base, cmd::TokenBlockEnd const&) -> VState {
          _bulk.commands.clear();
          clear(); // subs
          return State::Failed{};
        },
        [&](State::Base, cmd::TokenEnd const&) -> VState {
          if (_bulk.commands.size()){
            notify(_bulk);
            _bulk.commands.clear();
          }
          clear(); // subs
          return State::Finish{};
        },
        // Block:
        [&](State::Block & state, cmd::TokenCommand const& tok) -> VState {
          if (_bulk.commands.size() == 0)
            _bulk.time_stamp = std::chrono::system_clock::now();
          _bulk.commands.emplace_back(tok.value);
          return state;
        },
        [&](State::Block & state, cmd::TokenBlockBegin const&) -> VState {
          ++state.level;
          return state;
        },
        [&](State::Block & state, cmd::TokenBlockEnd const&) -> VState {
          --state.level;
          if (state.level == 0){
            notify(_bulk);
            _bulk.commands.clear();
            return State::Base{};
          }
          return state;
        },
        [&](State::Block, cmd::TokenEnd const&) -> VState {
          _bulk.commands.clear();
          clear(); // subs
          return State::Finish{};
        },
        // TODO: resolve case - call at failed or finished state... maybe throw an exception?
        [&](auto & state, auto const&) -> VState {
          _bulk.commands.clear();
          clear(); // subs
          return state;
        },
      }, _state, event.token);
      return getSubscriptionStatus();
  }
References _bulk, _BULK_SIZE, _state, core::PublisherMixin< BulkEvent >::clear(), bulk::BulkEvent::commands, getSubscriptionStatus(), core::PublisherMixin< BulkEvent >::notify(), and bulk::BulkEvent::time_stamp.
subscribe() [1/2]
void core::PublisherMixin< BulkEvent >::subscribe (SPtrSubscriber && subscriber) inline inherited
Definition at line 29 of file publisher.hpp.
{
    if (_subs.end() == _findSteady(subscriber->getSubscriberID())) {
      _subs.emplace_back(std::forward<SPtrSubscriber>(subscriber));
    }
  }
subscribe() [2/2]
void core::PublisherMixin< BulkEvent >::subscribe (SPtrSubscriber const & subscriber, bool own) inline inherited
Definition at line 19 of file publisher.hpp.
{
    if (_subs.end() == _findSteady(subscriber->getSubscriberID())) {
      // _subs.emplace_back((own) ? subscriber : WPtrSubscriber(subscriber));
      if (own)
        _subs.emplace_back(subscriber);
      else
        _subs.emplace_back(WPtrSubscriber(subscriber));
    }
  }
unsubscribe()
void core::PublisherMixin< BulkEvent >::unsubscribe (SPtrSubscriber const & subscriber) inline inherited
Definition at line 40 of file publisher.hpp.
{ _subs.erase(_findSteady(subscriber->getSubscriberID())); }
Member Data Documentation
_bulk
BulkEvent bulk::provider::BulkTranslator::_bulk private
Definition at line 118 of file bulk_translator.hpp.
Referenced by BulkTranslator(), and onEvent().
_BULK_SIZE
const size_t bulk::provider::BulkTranslator::_BULK_SIZE private
Definition at line 100 of file bulk_translator.hpp.
Referenced by BulkTranslator(), and onEvent().
_id
std::string core::SubscriberBase< cmd::TokenEvent >::_id private inherited
Definition at line 64 of file subscriber.hpp.
_state
VState bulk::provider::BulkTranslator::_state private
Definition at line 117 of file bulk_translator.hpp.
Referenced by getSubscriptionStatus(), and onEvent().
_subs
std::list<VPtrSubscriber> core::PublisherMixin< BulkEvent >::_subs private inherited
Definition at line 111 of file publisher.hpp.
The documentation for this class was generated from the following file:
src/bulk/provider/bulk_translator.hpp