bulk: logs::FileWriter Class Reference
logs::FileWriter Class Reference final
#include "file_writer.hpp"
Public Member Functions
core::SubscriptionStatus getSubscriptionStatus () noexcept override
Get Subscriber current State object.
void setSubscriptionStatus (core::SubscriptionStatus state) noexcept
core::SubscriptionStatus onEvent (bulk::BulkEvent const &event) override
Main Subscription Method.
virtual std::string getSubscriberID () final
Get the Subscriber Id object (internal usage for subsciber identification)
Static Public Member Functions
static auto create (std::string_view output_directory, std::string_view name="")
Private Member Functions
FileWriter (std::string_view local_name="", std::string_view output_directory="")
std::string getSubscriberName () const noexcept override
Get Subscriber Name (local within derived type)
size_t _instanceNum () const
Private Attributes
fs::path const _output_dir
std::string const _local_name
std::string const _name
size_t _bulk_counter = 0
core::SubscriptionStatus _subs_state
std::string _id
Detailed Description
Definition at line 15 of file file_writer.hpp.
Constructor & Destructor Documentation
FileWriter()
logs::FileWriter::FileWriter (std::string_view local_name = "", std::string_view output_directory = "") inline private
Definition at line 47 of file file_writer.hpp.
      : _output_dir{std::filesystem::canonical(output_directory)},
        _local_name{local_name.size() ? local_name : std::to_string(_instanceNum())},
        _name{std::format("{}.{}", _output_dir.c_str(), _local_name)},
        _subs_state{core::SubscriptionStatus::READY} {}
Member Function Documentation
_instanceNum()
size_t logs::FileWriter::_instanceNum () const inline private
Definition at line 55 of file file_writer.hpp.
{
    static size_t _counter = 0;
    return ++_counter;
  }
create()
static auto logs::FileWriter::create (std::string_view output_directory, std::string_view name = "") inline static
Definition at line 17 of file file_writer.hpp.
{
    return std::shared_ptr<FileWriter>(new FileWriter(output_directory, name));
  }
Referenced by main().
getSubscriberID()
virtual std::string core::SubscriberBase< bulk::BulkEvent >::getSubscriberID () inline final virtual inherited
Get the Subscriber Id object (internal usage for subsciber identification)
= {typeid(*this).name()}.{this->getSubscriberLocalName()}
Returns
std::string
Definition at line 47 of file subscriber.hpp.
{
    if (_id == "") _id = std::format("{}.{}", typeid(*this).name(), this->getSubscriberName());
    return _id;
  }
getSubscriberName()
std::string logs::FileWriter::getSubscriberName () const inline override private virtual noexcept
Get Subscriber Name (local within derived type)
applied as a suffix to typeid(*this) to identify subscribers of the same type
Returns
* std::string
Reimplemented from core::SubscriberBase< bulk::BulkEvent >.
Definition at line 53 of file file_writer.hpp.
{ return _name; }
References _name.
getSubscriptionStatus()
core::SubscriptionStatus logs::FileWriter::getSubscriptionStatus () inline override virtual noexcept
Get Subscriber current State object.
used by publisher before calling onEvent method state management is done in derived classes as needed (see file_writer.hpp)
Returns
SubscriptionStatus
Reimplemented from core::SubscriberBase< bulk::BulkEvent >.
Definition at line 21 of file file_writer.hpp.
{ return _subs_state; }
References _subs_state.
Referenced by onEvent().
onEvent()
core::SubscriptionStatus logs::FileWriter::onEvent (bulk::BulkEvent const & event) inline override virtual
Main Subscription Method.
if exception is thrown then publisher will unsubscribe this subscriber on its side imediatly but to unsubscribe in normal way it's better just to return 'SubscriptionStatus::CANCEL' status
Parameters
event
Returns
SubscriptionStatus state after handling onEvent method
Implements core::SubscriberBase< bulk::BulkEvent >.
Definition at line 25 of file file_writer.hpp.
{
    if (core::SubscriptionStatus::READY == getSubscriptionStatus()) {
      auto ts = std::to_string(
          std::chrono::duration_cast<std::chrono::milliseconds>(event.time_stamp.time_since_epoch()).count());
      std::ofstream fw(std::format("{}/{}_bulk{}_{}.log", _output_dir.c_str(), _local_name, ++_bulk_counter, ts));
      if (!fw.is_open()) {
        setSubscriptionStatus(core::SubscriptionStatus::CANCEL);
      } else {
        bulk::print(event, fw);
        fw.close();
      }
    }
    return getSubscriptionStatus();
  }
References _bulk_counter, _local_name, _output_dir, core::CANCEL, getSubscriptionStatus(), bulk::print(), core::READY, setSubscriptionStatus(), and bulk::BulkEvent::time_stamp.
setSubscriptionStatus()
void logs::FileWriter::setSubscriptionStatus (core::SubscriptionStatus state) inline noexcept
Definition at line 23 of file file_writer.hpp.
{ _subs_state = state; }
References _subs_state.
Referenced by onEvent().
Member Data Documentation
_bulk_counter
size_t logs::FileWriter::_bulk_counter = 0 private
Definition at line 44 of file file_writer.hpp.
Referenced by onEvent().
_id
std::string core::SubscriberBase< bulk::BulkEvent >::_id private inherited
Definition at line 64 of file subscriber.hpp.
_local_name
std::string const logs::FileWriter::_local_name private
Definition at line 42 of file file_writer.hpp.
Referenced by onEvent().
_name
std::string const logs::FileWriter::_name private
Definition at line 43 of file file_writer.hpp.
Referenced by getSubscriberName().
_output_dir
fs::path const logs::FileWriter::_output_dir private
Definition at line 41 of file file_writer.hpp.
Referenced by onEvent().
_subs_state
core::SubscriptionStatus logs::FileWriter::_subs_state private
Definition at line 45 of file file_writer.hpp.
Referenced by getSubscriptionStatus(), and setSubscriptionStatus().
The documentation for this class was generated from the following file:
src/logs/file_writer.hpp