bulk: logs::OutputStreamWriter Class Reference
logs::OutputStreamWriter Class Reference final
#include "ostream_writer.hpp"
Public Member Functions
core::SubscriptionStatus onEvent (bulk::BulkEvent const &event) override
Main Subscription Method.
core::SubscriptionStatus onEvent (cmd::TokenEvent const &event) override
Main Subscription Method.
virtual SubscriptionStatus getSubscriptionStatus () noexcept
Get Subscriber current State object.
virtual std::string getSubscriberID () final
Get the Subscriber Id object (internal usage for subsciber identification)
virtual SubscriptionStatus getSubscriptionStatus () noexcept
Get Subscriber current State object.
virtual std::string getSubscriberID () final
Get the Subscriber Id object (internal usage for subsciber identification)
Static Public Member Functions
static std::shared_ptr< OutputStreamWriter > create (std::ostream &out, std::string_view local_name="")
Private Member Functions
OutputStreamWriter (std::ostream &out, std::string_view local_name)
std::string getSubscriberName () const noexcept override
Get Subscriber Name (local within derived type)
Private Attributes
std::ostream & _out
std::string const _name
std::string _id
Detailed Description
Definition at line 12 of file ostream_writer.hpp.
Constructor & Destructor Documentation
OutputStreamWriter()
logs::OutputStreamWriter::OutputStreamWriter (std::ostream & out, std::string_view local_name) inline private
Definition at line 35 of file ostream_writer.hpp.
      : _out{out}, _name{std::format("{}.{}", typeid(out).name(), local_name)} {}
Member Function Documentation
create()
static std::shared_ptr< OutputStreamWriter > logs::OutputStreamWriter::create (std::ostream & out, std::string_view local_name = "") inline static
Definition at line 16 of file ostream_writer.hpp.
{
    return std::shared_ptr<OutputStreamWriter>(new OutputStreamWriter(out, local_name));
  }
Referenced by main().
getSubscriberID() [1/2]
virtual std::string core::SubscriberBase< cmd::TokenEvent >::getSubscriberID () inline final virtual inherited
Get the Subscriber Id object (internal usage for subsciber identification)
= {typeid(*this).name()}.{this->getSubscriberLocalName()}
Returns
std::string
Definition at line 47 of file subscriber.hpp.
{
    if (_id == "") _id = std::format("{}.{}", typeid(*this).name(), this->getSubscriberName());
    return _id;
  }
getSubscriberID() [2/2]
virtual std::string core::SubscriberBase< bulk::BulkEvent >::getSubscriberID () inline final virtual inherited
Get the Subscriber Id object (internal usage for subsciber identification)
= {typeid(*this).name()}.{this->getSubscriberLocalName()}
Returns
std::string
Definition at line 47 of file subscriber.hpp.
{
    if (_id == "") _id = std::format("{}.{}", typeid(*this).name(), this->getSubscriberName());
    return _id;
  }
getSubscriberName()
std::string logs::OutputStreamWriter::getSubscriberName () const inline override private virtual noexcept
Get Subscriber Name (local within derived type)
applied as a suffix to typeid(*this) to identify subscribers of the same type
Returns
* std::string
Reimplemented from core::SubscriberBase< cmd::TokenEvent >.
Definition at line 38 of file ostream_writer.hpp.
{ return _name; }
References _name.
getSubscriptionStatus() [1/2]
virtual SubscriptionStatus core::SubscriberBase< cmd::TokenEvent >::getSubscriptionStatus () inline virtual noexcept inherited
Get Subscriber current State object.
used by publisher before calling onEvent method state management is done in derived classes as needed (see file_writer.hpp)
Returns
SubscriptionStatus
Reimplemented in bulk::provider::BulkTranslator.
Definition at line 39 of file subscriber.hpp.
{ return SubscriptionStatus::READY; }
getSubscriptionStatus() [2/2]
virtual SubscriptionStatus core::SubscriberBase< bulk::BulkEvent >::getSubscriptionStatus () inline virtual noexcept inherited
Get Subscriber current State object.
used by publisher before calling onEvent method state management is done in derived classes as needed (see file_writer.hpp)
Returns
SubscriptionStatus
Reimplemented in logs::FileWriter.
Definition at line 39 of file subscriber.hpp.
{ return SubscriptionStatus::READY; }
onEvent() [1/2]
core::SubscriptionStatus logs::OutputStreamWriter::onEvent (bulk::BulkEvent const & event) inline override virtual
Main Subscription Method.
if exception is thrown then publisher will unsubscribe this subscriber on its side imediatly but to unsubscribe in normal way it's better just to return 'SubscriptionStatus::CANCEL' status
Parameters
event
Returns
SubscriptionStatus state after handling onEvent method
Implements core::SubscriberBase< bulk::BulkEvent >.
Definition at line 20 of file ostream_writer.hpp.
{
    bulk::print(event, _out);
    return static_cast<core::SubscriberBase<bulk::BulkEvent>*>(this)
        ->getSubscriptionStatus();  // == core::SubscriptionStatus::READY;
  }
References _out, core::SubscriberBase< cmd::TokenEvent >::getSubscriptionStatus(), and bulk::print().
onEvent() [2/2]
core::SubscriptionStatus logs::OutputStreamWriter::onEvent (cmd::TokenEvent const & event) inline override virtual
Main Subscription Method.
if exception is thrown then publisher will unsubscribe this subscriber on its side imediatly but to unsubscribe in normal way it's better just to return 'SubscriptionStatus::CANCEL' status
Parameters
event
Returns
SubscriptionStatus state after handling onEvent method
Implements core::SubscriberBase< cmd::TokenEvent >.
Definition at line 25 of file ostream_writer.hpp.
{
    cmd::print(event, _out);
    return static_cast<core::SubscriberBase<cmd::TokenEvent>*>(this)
        ->getSubscriptionStatus();  // == core::SubscriptionStatus::READY;
  }
References _out, core::SubscriberBase< cmd::TokenEvent >::getSubscriptionStatus(), and cmd::print().
Member Data Documentation
_id
std::string core::SubscriberBase< cmd::TokenEvent >::_id private inherited
Definition at line 64 of file subscriber.hpp.
_name
std::string const logs::OutputStreamWriter::_name private
Definition at line 33 of file ostream_writer.hpp.
Referenced by getSubscriberName().
_out
std::ostream& logs::OutputStreamWriter::_out private
Definition at line 32 of file ostream_writer.hpp.
Referenced by onEvent(), and onEvent().
The documentation for this class was generated from the following file:
src/logs/ostream_writer.hpp