bulk: logs::ConsoleWriter Class Reference
logs::ConsoleWriter Class Reference final
#include "console_writer.hpp"
Public Member Functions
core::SubscriptionStatus onEvent (bulk::BulkEvent const &event) override
Main Subscription Method.
core::SubscriptionStatus onEvent (cmd::TokenEvent const &event) override
Main Subscription Method.
virtual SubscriptionStatus getSubscriptionStatus () noexcept
Get Subscriber current State object.
virtual std::string getSubscriberName () const noexcept
Get Subscriber Name (local within derived type)
virtual std::string _subscriberID () final
Get the Subscriber Id object (internal usage for subsciber identification)
virtual SubscriptionStatus getSubscriptionStatus () noexcept
Get Subscriber current State object.
virtual std::string getSubscriberName () const noexcept
Get Subscriber Name (local within derived type)
virtual std::string _subscriberID () final
Get the Subscriber Id object (internal usage for subsciber identification)
Static Public Member Functions
static std::shared_ptr< ConsoleWriter > create ()
Private Member Functions
ConsoleWriter ()
Private Attributes
std::string _id
Detailed Description
Definition at line 12 of file console_writer.hpp.
Constructor & Destructor Documentation
ConsoleWriter()
logs::ConsoleWriter::ConsoleWriter () inline private
Definition at line 32 of file console_writer.hpp.
{};
Referenced by create().
Member Function Documentation
_subscriberID() [1/2]
virtual std::string core::SubscriberBase< cmd::TokenEvent >::_subscriberID () inline final virtual inherited
Get the Subscriber Id object (internal usage for subsciber identification)
= {typeid(*this).name()}.{this->getSubscriberLocalName()}
Returns
std::string
Definition at line 55 of file subscriber.hpp.
{
    if (_id == "") _id = std::format("{}.{}", typeid(*this).name(), this->getSubscriberName());
    return _id;
  }
_subscriberID() [2/2]
virtual std::string core::SubscriberBase< bulk::BulkEvent >::_subscriberID () inline final virtual inherited
Get the Subscriber Id object (internal usage for subsciber identification)
= {typeid(*this).name()}.{this->getSubscriberLocalName()}
Returns
std::string
Definition at line 55 of file subscriber.hpp.
{
    if (_id == "") _id = std::format("{}.{}", typeid(*this).name(), this->getSubscriberName());
    return _id;
  }
create()
static std::shared_ptr< ConsoleWriter > logs::ConsoleWriter::create () inline static
Definition at line 16 of file console_writer.hpp.
{
    return std::shared_ptr<ConsoleWriter>(new ConsoleWriter());
  }
References ConsoleWriter().
Referenced by main().
getSubscriberName() [1/2]
virtual std::string core::SubscriberBase< cmd::TokenEvent >::getSubscriberName () const inline virtual noexcept inherited
Get Subscriber Name (local within derived type)
applied as a suffix to typeid(*this) to identify subscribers of the same type
Returns
* std::string
Definition at line 47 of file subscriber.hpp.
{ return ""; }
getSubscriberName() [2/2]
virtual std::string core::SubscriberBase< bulk::BulkEvent >::getSubscriberName () const inline virtual noexcept inherited
Get Subscriber Name (local within derived type)
applied as a suffix to typeid(*this) to identify subscribers of the same type
Returns
* std::string
Reimplemented in logs::FileWriter.
Definition at line 47 of file subscriber.hpp.
{ return ""; }
getSubscriptionStatus() [1/2]
virtual SubscriptionStatus core::SubscriberBase< cmd::TokenEvent >::getSubscriptionStatus () inline virtual noexcept inherited
Get Subscriber current State object.
used by publisher before calling onEvent method state management is done in derived classes as needed (see file_writer.hpp)
Returns
SubscriptionStatus
Reimplemented in bulk::provider::BulkTranslator.
Definition at line 39 of file subscriber.hpp.
{ return SubscriptionStatus::READY; }
getSubscriptionStatus() [2/2]
virtual SubscriptionStatus core::SubscriberBase< bulk::BulkEvent >::getSubscriptionStatus () inline virtual noexcept inherited
Get Subscriber current State object.
used by publisher before calling onEvent method state management is done in derived classes as needed (see file_writer.hpp)
Returns
SubscriptionStatus
Reimplemented in logs::FileWriter.
Definition at line 39 of file subscriber.hpp.
{ return SubscriptionStatus::READY; }
onEvent() [1/2]
core::SubscriptionStatus logs::ConsoleWriter::onEvent (bulk::BulkEvent const & event) inline override virtual
Main Subscription Method.
if exception is thrown then publisher will unsubscribe this subscriber on its side imediatly but to unsubscribe in normal way it's better just to return 'SubscriptionStatus::CANCEL' status
Parameters
event
Returns
SubscriptionStatus state after handling onEvent method
Implements core::SubscriberBase< bulk::BulkEvent >.
Definition at line 20 of file console_writer.hpp.
{
    bulk::print(event, std::cout);
    return core::SubscriptionStatus::READY;
    // || static_cast<core::SubscriberBase<bulk::BulkEvent>*>(this)->getSubscriptionStatus();
  }
References bulk::print(), and core::READY.
onEvent() [2/2]
core::SubscriptionStatus logs::ConsoleWriter::onEvent (cmd::TokenEvent const & event) inline override virtual
Main Subscription Method.
if exception is thrown then publisher will unsubscribe this subscriber on its side imediatly but to unsubscribe in normal way it's better just to return 'SubscriptionStatus::CANCEL' status
Parameters
event
Returns
SubscriptionStatus state after handling onEvent method
Implements core::SubscriberBase< cmd::TokenEvent >.
Definition at line 25 of file console_writer.hpp.
{
    cmd::print(event, std::cout);
    return core::SubscriptionStatus::READY;
    // || static_cast<core::SubscriberBase<cmd::Token>*>(this)->getSubscriptionStatus();
  }
References cmd::print(), and core::READY.
Member Data Documentation
_id
std::string core::SubscriberBase< cmd::TokenEvent >::_id private inherited
Definition at line 61 of file subscriber.hpp.
The documentation for this class was generated from the following file:
src/logs/console_writer.hpp