bulk: cmd::provider::ConsoleParser Class Reference
cmd::provider::ConsoleParser Class Reference final
Command parser from input stream.
#include "console_parser.hpp"
Public Types
using Subscriber = SubscriberBase< TokenEvent >
using WPtrSubscriber = std::weak_ptr< Subscriber >
using SPtrSubscriber = std::shared_ptr< Subscriber >
using VPtrSubscriber = std::variant< WPtrSubscriber, SPtrSubscriber >
Public Member Functions
ConsoleParser (ConsoleParser const &)=delete
ConsoleParser & operator= (ConsoleParser const &)=delete
~ConsoleParser ()
void run ()
parse all input stream passed to ctor while at least one subscriber is alive
void subscribe (SPtrSubscriber const &subscriber, bool own)
void subscribe (SPtrSubscriber &&subscriber)
bool hasSubscription ()
void unsubscribe (SPtrSubscriber const &subscriber)
void clear ()
Static Public Member Functions
static ConsoleParser & instance ()
Protected Member Functions
void notify (TokenEvent const &event)
Private Member Functions
ConsoleParser () noexcept
Token advance ()
std::optional< SPtrSubscriber > _getShared (VPtrSubscriber const &vptr)
auto _findSteady (std::string_view id)
void _refresh ()
Private Attributes
std::list< VPtrSubscriber > _subs
Detailed Description
Command parser from input stream.
to keep command stream consistency, parser must have exclusive access to stream resource
Definition at line 17 of file console_parser.hpp.
Member Typedef Documentation
SPtrSubscriber
using core::PublisherMixin< TokenEvent >::SPtrSubscriber = std::shared_ptr<Subscriber> inherited
Definition at line 14 of file publisher.hpp.
Subscriber
using core::PublisherMixin< TokenEvent >::Subscriber = SubscriberBase<TokenEvent > inherited
Definition at line 12 of file publisher.hpp.
VPtrSubscriber
using core::PublisherMixin< TokenEvent >::VPtrSubscriber = std::variant<WPtrSubscriber, SPtrSubscriber> inherited
Definition at line 15 of file publisher.hpp.
WPtrSubscriber
using core::PublisherMixin< TokenEvent >::WPtrSubscriber = std::weak_ptr<Subscriber> inherited
Definition at line 13 of file publisher.hpp.
Constructor & Destructor Documentation
ConsoleParser() [1/2]
cmd::provider::ConsoleParser::ConsoleParser (ConsoleParser const &) delete
~ConsoleParser()
cmd::provider::ConsoleParser::~ConsoleParser () inline
Definition at line 26 of file console_parser.hpp.
{}
ConsoleParser() [2/2]
cmd::provider::ConsoleParser::ConsoleParser () inline private noexcept
Definition at line 44 of file console_parser.hpp.
{}
Member Function Documentation
_findSteady()
auto core::PublisherMixin< TokenEvent >::_findSteady (std::string_view id) inline private inherited
Definition at line 86 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        if (spo.value()->getSubscriberID() == id) return it;
        ++it;
      } else {
        it = _subs.erase(it);
      }
    }
    return _subs.end();
  }
_getShared()
std::optional< SPtrSubscriber > core::PublisherMixin< TokenEvent >::_getShared (VPtrSubscriber const & vptr) inline private inherited
Definition at line 76 of file publisher.hpp.
{
    if (std::holds_alternative<WPtrSubscriber>(vptr)) {
      if (auto sp = std::get<WPtrSubscriber>(vptr).lock())
        return sp;
      else
        return std::nullopt;
    }
    return std::get<SPtrSubscriber>(vptr);
  }
_refresh()
void core::PublisherMixin< TokenEvent >::_refresh () inline private inherited
Definition at line 98 of file publisher.hpp.
                  {
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        if (SubscriptionStatus::CANCEL == spo.value()->getSubscriptionStatus())
          it = _subs.erase(it);
        else
          ++it;
      } else {
        it = _subs.erase(it);
      }
    }
  }
advance()
Token cmd::provider::ConsoleParser::advance () inline private
Definition at line 46 of file console_parser.hpp.
                  {
    if (std::string line; std::getline(std::cin, line)) {
      // utils::to_lower(utils::trim(line));
      utils::trim(line);
      if (line.size() > 0) {
        if (line.size() == 1) {
          switch (line[0]) {
            case '{':
              return TokenBlockBegin{};
            case '}':
              return TokenBlockEnd{};
            default:
              return TokenCommand{line};
          }
        } else
          return TokenCommand{line};
      } else
        return TokenUnknown{};
    } else
      return TokenEnd{};
  }
References utils::trim().
Referenced by run().
clear()
void core::PublisherMixin< TokenEvent >::clear () inline inherited
Definition at line 42 of file publisher.hpp.
{ _subs.clear(); }
hasSubscription()
bool core::PublisherMixin< TokenEvent >::hasSubscription () inline inherited
Definition at line 35 of file publisher.hpp.
{
    _refresh();
    return (_subs.size() > 0);
  }
instance()
static ConsoleParser & cmd::provider::ConsoleParser::instance () inline static
Definition at line 19 of file console_parser.hpp.
{
    static ConsoleParser inst{};
    return inst;
  }
Referenced by main().
notify()
void core::PublisherMixin< TokenEvent >::notify (TokenEvent const & event) inline protected inherited
Definition at line 47 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        auto& sp = spo.value();
        switch (sp->getSubscriptionStatus()) {
          case SubscriptionStatus::READY:
            try {
              if (SubscriptionStatus::CANCEL == sp->onEvent(event))
                it = _subs.erase(it);
              else
                ++it;
            } catch (...) {
              it = _subs.erase(it);
            }
            break;
          case SubscriptionStatus::SUSPEND:
            ++it;
            break;
          case SubscriptionStatus::CANCEL:
            it = _subs.erase(it);
            break;
        }
      } else {
        it = _subs.erase(it);
      }
    }
  }
operator=()
ConsoleParser & cmd::provider::ConsoleParser::operator= (ConsoleParser const &) delete
run()
void cmd::provider::ConsoleParser::run () inline
parse all input stream passed to ctor while at least one subscriber is alive
Definition at line 32 of file console_parser.hpp.
             {
    size_t index = 0;
    Token tok = TokenUnknown{};
    while (hasSubscription() && !std::holds_alternative<TokenEnd>(tok)) {
      tok = advance();
      if (!std::holds_alternative<TokenUnknown>(tok)) {
        notify(TokenEvent{tok, ++index});
      }
    }
  }
References advance(), core::PublisherMixin< TokenEvent >::hasSubscription(), and core::PublisherMixin< TokenEvent >::notify().
subscribe() [1/2]
void core::PublisherMixin< TokenEvent >::subscribe (SPtrSubscriber && subscriber) inline inherited
Definition at line 29 of file publisher.hpp.
{
    if (_subs.end() == _findSteady(subscriber->getSubscriberID())) {
      _subs.emplace_back(std::forward<SPtrSubscriber>(subscriber));
    }
  }
subscribe() [2/2]
void core::PublisherMixin< TokenEvent >::subscribe (SPtrSubscriber const & subscriber, bool own) inline inherited
Definition at line 19 of file publisher.hpp.
{
    if (_subs.end() == _findSteady(subscriber->getSubscriberID())) {
      // _subs.emplace_back((own) ? subscriber : WPtrSubscriber(subscriber));
      if (own)
        _subs.emplace_back(subscriber);
      else
        _subs.emplace_back(WPtrSubscriber(subscriber));
    }
  }
unsubscribe()
void core::PublisherMixin< TokenEvent >::unsubscribe (SPtrSubscriber const & subscriber) inline inherited
Definition at line 40 of file publisher.hpp.
{ _subs.erase(_findSteady(subscriber->getSubscriberID())); }
Member Data Documentation
_subs
std::list<VPtrSubscriber> core::PublisherMixin< TokenEvent >::_subs private inherited
Definition at line 111 of file publisher.hpp.
The documentation for this class was generated from the following file:
src/cmd/provider/console_parser.hpp