bulk: cmd::provider::InputStreamParser Class Reference
cmd::provider::InputStreamParser Class Reference final
Command parser from input stream.
#include "istream_parser.hpp"
Public Types
using Subscriber = SubscriberBase< TokenEvent >
using WPtrSubscriber = std::weak_ptr< Subscriber >
using SPtrSubscriber = std::shared_ptr< Subscriber >
using VPtrSubscriber = std::variant< WPtrSubscriber, SPtrSubscriber >
Public Member Functions
InputStreamParser (InputStreamParser const &)=delete
InputStreamParser & operator= (InputStreamParser const &)=delete
~InputStreamParser ()
void run ()
void subscribe (SPtrSubscriber const &subscriber, bool own)
void subscribe (SPtrSubscriber &&subscriber)
void unsubscribe (SPtrSubscriber const &subscriber)
void clear ()
Static Public Member Functions
static InputStreamParser & instance ()
Protected Member Functions
void notify (const TokenEvent &event)
Private Member Functions
InputStreamParser (std::istream &in=std::cin, size_t index_from=0) noexcept
Token advance ()
std::optional< SPtrSubscriber > _getSPtrSubscriber (std::list< VPtrSubscriber >::iterator &it)
auto _find (std::string_view id)
Private Attributes
std::istream & _in
size_t _index
std::list< VPtrSubscriber > _subs
Detailed Description
Command parser from input stream.
to keep command stream consistency, parser must have exclusive access to stream resource.
Definition at line 17 of file istream_parser.hpp.
Member Typedef Documentation
SPtrSubscriber
using core::PublisherMixin< TokenEvent >::SPtrSubscriber = std::shared_ptr<Subscriber> inherited
Definition at line 15 of file publisher.hpp.
Subscriber
using core::PublisherMixin< TokenEvent >::Subscriber = SubscriberBase<TokenEvent > inherited
Definition at line 13 of file publisher.hpp.
VPtrSubscriber
using core::PublisherMixin< TokenEvent >::VPtrSubscriber = std::variant<WPtrSubscriber, SPtrSubscriber> inherited
Definition at line 16 of file publisher.hpp.
WPtrSubscriber
using core::PublisherMixin< TokenEvent >::WPtrSubscriber = std::weak_ptr<Subscriber> inherited
Definition at line 14 of file publisher.hpp.
Constructor & Destructor Documentation
InputStreamParser() [1/2]
cmd::provider::InputStreamParser::InputStreamParser (InputStreamParser const &) delete
~InputStreamParser()
cmd::provider::InputStreamParser::~InputStreamParser () inline
Definition at line 27 of file istream_parser.hpp.
{}
InputStreamParser() [2/2]
cmd::provider::InputStreamParser::InputStreamParser (std::istream & in = std::cin, size_t index_from = 0) inline private noexcept
Definition at line 43 of file istream_parser.hpp.
: _in{in}, _index{index_from} {}
Member Function Documentation
_find()
auto core::PublisherMixin< TokenEvent >::_find (std::string_view id) inline private inherited
Definition at line 72 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getSPtrSubscriber(it)) {
        if (spo.value()->_subscriberID() == id) return it;
        ++it;
      } else {
        it = _subs.erase(it);
      }
    }
    return _subs.end();
  }
_getSPtrSubscriber()
std::optional< SPtrSubscriber > core::PublisherMixin< TokenEvent >::_getSPtrSubscriber (std::list< VPtrSubscriber >::iterator & it) inline private inherited
Definition at line 64 of file publisher.hpp.
{
    if (std::holds_alternative<WPtrSubscriber>(*it)) {
      auto sp = std::get<WPtrSubscriber>(*it).lock();
      return sp ? std::optional<SPtrSubscriber>(sp) : std::nullopt;
    }
    return std::get<SPtrSubscriber>(*it);
  }
advance()
Token cmd::provider::InputStreamParser::advance () inline private
Definition at line 45 of file istream_parser.hpp.
                  {
    if (std::string line; std::getline(_in, line)) {
      to_lower(trim(line));
      if (line.size() > 0) {
        if (line.size() == 1) {
          switch (line[0]) {
            case '{':
              return TokenBlockBegin{};
            case '}':
              return TokenBlockEnd{};
            default:
              return TokenCommand{line};
          }
        } else
          return TokenCommand{line};
      } else
        return TokenUnknown{};
    } else
      return TokenEnd{};
  }
References _in, to_lower(), and trim().
Referenced by run().
clear()
void core::PublisherMixin< TokenEvent >::clear () inline inherited
Definition at line 32 of file publisher.hpp.
{ _subs.clear(); }
instance()
static InputStreamParser & cmd::provider::InputStreamParser::instance () inline static
Definition at line 20 of file istream_parser.hpp.
{
    static InputStreamParser inst;
    return inst;
  }
Referenced by main().
notify()
void core::PublisherMixin< TokenEvent >::notify (const TokenEvent & event) inline protected inherited
Definition at line 37 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getSPtrSubscriber(it)) {
        auto& sp = spo.value();
        switch (sp->getSubscriptionStatus()) {
          case SubscriptionStatus::READY:
            try {
              if (SubscriptionStatus::CANCEL == sp->onEvent(event))
                it = _subs.erase(it);
              else
                ++it;
            } catch (...) {
              it = _subs.erase(it);
            }
            break;
          case SubscriptionStatus::SUSPEND:
            ++it;
            break;
          case SubscriptionStatus::CANCEL:
            it = _subs.erase(it);
            break;
        }
      }
    }
  }
operator=()
InputStreamParser & cmd::provider::InputStreamParser::operator= (InputStreamParser const &) delete
run()
void cmd::provider::InputStreamParser::run () inline
Definition at line 29 of file istream_parser.hpp.
             {
    Token tok = TokenUnknown{};
    while (!std::holds_alternative<TokenEnd>(tok)) {
      tok = advance();
      if (!std::holds_alternative<TokenUnknown>(tok)) {
        notify(TokenEvent{tok, ++_index});
      }
    }
  }
References _index, advance(), and core::PublisherMixin< TokenEvent >::notify().
subscribe() [1/2]
void core::PublisherMixin< TokenEvent >::subscribe (SPtrSubscriber && subscriber) inline inherited
Definition at line 25 of file publisher.hpp.
{
    if (_subs.end() == _find(subscriber->_subscriberID()))
      _subs.emplace_back(std::forward<SPtrSubscriber>(subscriber));
  }
subscribe() [2/2]
void core::PublisherMixin< TokenEvent >::subscribe (SPtrSubscriber const & subscriber, bool own) inline inherited
Definition at line 20 of file publisher.hpp.
{
    if (_subs.end() == _find(subscriber->_subscriberID()))
      _subs.emplace_back(own ? subscriber : WPtrSubscriber(subscriber));
  }
unsubscribe()
void core::PublisherMixin< TokenEvent >::unsubscribe (SPtrSubscriber const & subscriber) inline inherited
Definition at line 30 of file publisher.hpp.
{ _subs.erase(_find(subscriber->_subscriberID())); }
Member Data Documentation
_in
std::istream& cmd::provider::InputStreamParser::_in private
Definition at line 40 of file istream_parser.hpp.
Referenced by advance().
_index
size_t cmd::provider::InputStreamParser::_index private
Definition at line 41 of file istream_parser.hpp.
Referenced by run().
_subs
std::list<VPtrSubscriber> core::PublisherMixin< TokenEvent >::_subs private inherited
Definition at line 84 of file publisher.hpp.
The documentation for this class was generated from the following file:
src/cmd/provider/istream_parser.hpp