bulk: core::PublisherMixin< EventType > Class Template Reference
core::PublisherMixin< EventType > Class Template Reference
#include "publisher.hpp"
Public Types
using Subscriber = SubscriberBase< EventType >
using WPtrSubscriber = std::weak_ptr< Subscriber >
using SPtrSubscriber = std::shared_ptr< Subscriber >
using VPtrSubscriber = std::variant< WPtrSubscriber, SPtrSubscriber >
Public Member Functions
virtual ~PublisherMixin ()=default
void subscribe (SPtrSubscriber const &subscriber, bool own)
void subscribe (SPtrSubscriber &&subscriber)
bool hasSubscription ()
void unsubscribe (SPtrSubscriber const &subscriber)
void clear ()
Protected Member Functions
PublisherMixin ()
void notify (EventType const &event)
Private Member Functions
std::optional< SPtrSubscriber > _getShared (VPtrSubscriber const &vptr)
auto _findSteady (std::string_view id)
void _refresh ()
Private Attributes
std::list< VPtrSubscriber > _subs
Detailed Description
template<typename EventType>
class core::PublisherMixin< EventType >
Definition at line 10 of file publisher.hpp.
Member Typedef Documentation
SPtrSubscriber
template<typename EventType > using core::PublisherMixin< EventType >::SPtrSubscriber = std::shared_ptr<Subscriber>
Definition at line 14 of file publisher.hpp.
Subscriber
template<typename EventType > using core::PublisherMixin< EventType >::Subscriber = SubscriberBase<EventType>
Definition at line 12 of file publisher.hpp.
VPtrSubscriber
template<typename EventType > using core::PublisherMixin< EventType >::VPtrSubscriber = std::variant<WPtrSubscriber, SPtrSubscriber>
Definition at line 15 of file publisher.hpp.
WPtrSubscriber
template<typename EventType > using core::PublisherMixin< EventType >::WPtrSubscriber = std::weak_ptr<Subscriber>
Definition at line 13 of file publisher.hpp.
Constructor & Destructor Documentation
~PublisherMixin()
template<typename EventType > virtual core::PublisherMixin< EventType >::~PublisherMixin () virtual default
PublisherMixin()
template<typename EventType > core::PublisherMixin< EventType >::PublisherMixin () inline protected
Definition at line 45 of file publisher.hpp.
{}
Member Function Documentation
_findSteady()
template<typename EventType > auto core::PublisherMixin< EventType >::_findSteady (std::string_view id) inline private
Definition at line 86 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        if (spo.value()->getSubscriberID() == id) return it;
        ++it;
      } else {
        it = _subs.erase(it);
      }
    }
    return _subs.end();
  }
References core::PublisherMixin< EventType >::_getShared(), and core::PublisherMixin< EventType >::_subs.
Referenced by core::PublisherMixin< EventType >::subscribe(), core::PublisherMixin< EventType >::subscribe(), and core::PublisherMixin< EventType >::unsubscribe().
_getShared()
template<typename EventType > std::optional< SPtrSubscriber > core::PublisherMixin< EventType >::_getShared (VPtrSubscriber const & vptr) inline private
Definition at line 76 of file publisher.hpp.
{
    if (std::holds_alternative<WPtrSubscriber>(vptr)) {
      if (auto sp = std::get<WPtrSubscriber>(vptr).lock())
        return sp;
      else
        return std::nullopt;
    }
    return std::get<SPtrSubscriber>(vptr);
  }
Referenced by core::PublisherMixin< EventType >::_findSteady(), core::PublisherMixin< EventType >::_refresh(), and core::PublisherMixin< EventType >::notify().
_refresh()
template<typename EventType > void core::PublisherMixin< EventType >::_refresh () inline private
Definition at line 98 of file publisher.hpp.
                  {
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        if (SubscriptionStatus::CANCEL == spo.value()->getSubscriptionStatus())
          it = _subs.erase(it);
        else
          ++it;
      } else {
        it = _subs.erase(it);
      }
    }
  }
References core::PublisherMixin< EventType >::_getShared(), core::PublisherMixin< EventType >::_subs, and core::CANCEL.
Referenced by core::PublisherMixin< EventType >::hasSubscription().
clear()
template<typename EventType > void core::PublisherMixin< EventType >::clear () inline
Definition at line 42 of file publisher.hpp.
{ _subs.clear(); }
References core::PublisherMixin< EventType >::_subs.
hasSubscription()
template<typename EventType > bool core::PublisherMixin< EventType >::hasSubscription () inline
Definition at line 35 of file publisher.hpp.
{
    _refresh();
    return (_subs.size() > 0);
  }
References core::PublisherMixin< EventType >::_refresh(), and core::PublisherMixin< EventType >::_subs.
notify()
template<typename EventType > void core::PublisherMixin< EventType >::notify (EventType const & event) inline protected
Definition at line 47 of file publisher.hpp.
{
    for (auto it = _subs.begin(); it != _subs.end();) {
      if (auto spo = _getShared(*it)) {
        auto& sp = spo.value();
        switch (sp->getSubscriptionStatus()) {
          case SubscriptionStatus::READY:
            try {
              if (SubscriptionStatus::CANCEL == sp->onEvent(event))
                it = _subs.erase(it);
              else
                ++it;
            } catch (...) {
              it = _subs.erase(it);
            }
            break;
          case SubscriptionStatus::SUSPEND:
            ++it;
            break;
          case SubscriptionStatus::CANCEL:
            it = _subs.erase(it);
            break;
        }
      } else {
        it = _subs.erase(it);
      }
    }
  }
References core::PublisherMixin< EventType >::_getShared(), core::PublisherMixin< EventType >::_subs, core::CANCEL, core::READY, and core::SUSPEND.
subscribe() [1/2]
template<typename EventType > void core::PublisherMixin< EventType >::subscribe (SPtrSubscriber && subscriber) inline
Definition at line 29 of file publisher.hpp.
{
    if (_subs.end() == _findSteady(subscriber->getSubscriberID())) {
      _subs.emplace_back(std::forward<SPtrSubscriber>(subscriber));
    }
  }
References core::PublisherMixin< EventType >::_findSteady(), and core::PublisherMixin< EventType >::_subs.
subscribe() [2/2]
template<typename EventType > void core::PublisherMixin< EventType >::subscribe (SPtrSubscriber const & subscriber, bool own) inline
Definition at line 19 of file publisher.hpp.
{
    if (_subs.end() == _findSteady(subscriber->getSubscriberID())) {
      // _subs.emplace_back((own) ? subscriber : WPtrSubscriber(subscriber));
      if (own)
        _subs.emplace_back(subscriber);
      else
        _subs.emplace_back(WPtrSubscriber(subscriber));
    }
  }
References core::PublisherMixin< EventType >::_findSteady(), and core::PublisherMixin< EventType >::_subs.
unsubscribe()
template<typename EventType > void core::PublisherMixin< EventType >::unsubscribe (SPtrSubscriber const & subscriber) inline
Definition at line 40 of file publisher.hpp.
{ _subs.erase(_findSteady(subscriber->getSubscriberID())); }
References core::PublisherMixin< EventType >::_findSteady(), and core::PublisherMixin< EventType >::_subs.
Member Data Documentation
_subs
template<typename EventType > std::list<VPtrSubscriber> core::PublisherMixin< EventType >::_subs private
Definition at line 111 of file publisher.hpp.
Referenced by core::PublisherMixin< EventType >::_findSteady(), core::PublisherMixin< EventType >::_refresh(), core::PublisherMixin< EventType >::clear(), core::PublisherMixin< EventType >::hasSubscription(), core::PublisherMixin< EventType >::notify(), core::PublisherMixin< EventType >::subscribe(), core::PublisherMixin< EventType >::subscribe(), and core::PublisherMixin< EventType >::unsubscribe().
The documentation for this class was generated from the following file:
src/core/publisher.hpp