bulk: cmd Namespace Reference
cmd Namespace Reference
Namespaces
namespace provider
Classes
struct TokenBlockBegin
{
struct TokenBlockEnd
}
struct TokenCommand
any string (f.e. cmdN ...)
struct TokenEnd
EOF.
struct TokenEvent
struct TokenUnknown
in this task it's equal to empty (or with witespaces) or none string
Typedefs
using Token = std::variant< TokenBlockBegin, TokenBlockEnd, TokenCommand, TokenEnd, TokenUnknown >
Functions
std::string to_string (Token const &tok)
void print (TokenEvent const &event, std::ostream &out)
Class Documentation
cmd::TokenBlockBegin
struct cmd::TokenBlockBegin
{
Definition at line 12 of file token.hpp.
cmd::TokenBlockEnd
struct cmd::TokenBlockEnd
}
Definition at line 13 of file token.hpp.
cmd::TokenCommand
struct cmd::TokenCommand
any string (f.e. cmdN ...)
Definition at line 14 of file token.hpp.
Class Members
string value
cmd::TokenEnd
struct cmd::TokenEnd
EOF.
Definition at line 18 of file token.hpp.
cmd::TokenEvent
struct cmd::TokenEvent
Definition at line 7 of file token_event.hpp.
Class Members
size_t index
Token token
cmd::TokenUnknown
struct cmd::TokenUnknown
in this task it's equal to empty (or with witespaces) or none string
Definition at line 17 of file token.hpp.
Typedef Documentation
Token
using cmd::Token = typedef std::variant<TokenBlockBegin, TokenBlockEnd, TokenCommand, TokenEnd, TokenUnknown>
Definition at line 20 of file token.hpp.
Function Documentation
print()
void cmd::print (TokenEvent const & event, std::ostream & out) inline
Definition at line 12 of file token_event.hpp.
{
  out << "#" << event.index << " > " << to_string(event.token) << std::endl;
}
References to_string(), and cmd::TokenEvent::token.
Referenced by logs::OutputStreamWriter::onEvent().
to_string()
std::string cmd::to_string (Token const & tok) inline
Definition at line 23 of file token.hpp.
{
  return std::visit(utils::overload{
      [](TokenBlockBegin const&) -> std::string { return "BLOCK_BEGIN ( { )"; },
      [](TokenBlockEnd const&) -> std::string { return "BLOCK_END ( } )"; },
      [](TokenCommand const& tok) -> std::string { return std::format("COMMAND ( {} )", tok.value); },
      [](TokenEnd const&) -> std::string { return "END ( . )"; },
      [](TokenUnknown const&) -> std::string { return "UNKNOWN ( ? )"; }
    }, tok);
}
Referenced by print().