bulk: info Namespace Reference
info Namespace Reference
Functions
constexpr std::string_view info_project_author ()
constexpr std::string_view info_project_repository_url ()
constexpr std::string_view info_project_repository_branch ()
constexpr std::string_view info_project_revision ()
constexpr std::string_view info_project_revision_datetime ()
constexpr std::string_view info_project_revision_history ()
constexpr std::string_view info_project_version ()
std::string info_project_full ()
Variables
const char PROJECT_AUTHOR [] =
const char PROJECT_REPOSITORY_URL [] = ""
const char PROJECT_REPOSITORY_BRANCH [] = "HEAD"
const char PROJECT_REVISION [] =
const char PROJECT_REVISION_DATETIME [] =
const char PROJECT_REVISION_HISTORY [] = R"()"
const char PROJECT_VERSION [] = ""
Function Documentation
info_project_author()
constexpr std::string_view info::info_project_author () constexpr
Definition at line 7 of file version.h.
{ return PROJECT_AUTHOR; }
References PROJECT_AUTHOR.
Referenced by info_project_full().
info_project_full()
std::string info::info_project_full ()
Definition at line 5 of file version.cpp.
{
  std::stringstream ss;
  ss << "author: " << info_project_author() << std::endl;
  ss << "url: " << info_project_repository_url() << std::endl;
  ss << "branch: " << info_project_repository_branch() << std::endl;
  ss << "rev: " << info_project_revision() << std::endl;
  ss << "rev date: " << info_project_revision_datetime() << std::endl;
  ss << "rev hist: " << info_project_revision_history() << std::endl;
  return ss.str();
}
References info_project_author(), info_project_repository_branch(), info_project_repository_url(), info_project_revision(), info_project_revision_datetime(), and info_project_revision_history().
Referenced by args::info_requested(), and TEST().
info_project_repository_branch()
constexpr std::string_view info::info_project_repository_branch () constexpr
Definition at line 9 of file version.h.
{ return PROJECT_REPOSITORY_BRANCH; }
References PROJECT_REPOSITORY_BRANCH.
Referenced by info_project_full().
info_project_repository_url()
constexpr std::string_view info::info_project_repository_url () constexpr
Definition at line 8 of file version.h.
{ return PROJECT_REPOSITORY_URL; }
References PROJECT_REPOSITORY_URL.
Referenced by info_project_full().
info_project_revision()
constexpr std::string_view info::info_project_revision () constexpr
Definition at line 10 of file version.h.
{ return PROJECT_REVISION; }
References PROJECT_REVISION.
Referenced by info_project_full().
info_project_revision_datetime()
constexpr std::string_view info::info_project_revision_datetime () constexpr
Definition at line 11 of file version.h.
{ return PROJECT_REVISION_DATETIME; }
References PROJECT_REVISION_DATETIME.
Referenced by info_project_full().
info_project_revision_history()
constexpr std::string_view info::info_project_revision_history () constexpr
Definition at line 12 of file version.h.
{ return PROJECT_REVISION_HISTORY; }
References PROJECT_REVISION_HISTORY.
Referenced by info_project_full().
info_project_version()
constexpr std::string_view info::info_project_version () constexpr
Definition at line 13 of file version.h.
{ return PROJECT_VERSION; }
References PROJECT_VERSION.
Referenced by args::info_requested(), and TEST().
Variable Documentation
PROJECT_AUTHOR
const char info::PROJECT_AUTHOR[] =
Definition at line 5 of file config.h.
Referenced by info_project_author().
PROJECT_REPOSITORY_BRANCH
const char info::PROJECT_REPOSITORY_BRANCH[] = "HEAD"
Definition at line 7 of file config.h.
Referenced by info_project_repository_branch().
PROJECT_REPOSITORY_URL
const char info::PROJECT_REPOSITORY_URL[] = ""
Definition at line 6 of file config.h.
Referenced by info_project_repository_url().
PROJECT_REVISION
const char info::PROJECT_REVISION[] =
Definition at line 8 of file config.h.
Referenced by info_project_revision().
PROJECT_REVISION_DATETIME
const char info::PROJECT_REVISION_DATETIME[] =
Definition at line 9 of file config.h.
Referenced by info_project_revision_datetime().
PROJECT_REVISION_HISTORY
const char info::PROJECT_REVISION_HISTORY[] = R"()"
Definition at line 10 of file config.h.
Referenced by info_project_revision_history().
PROJECT_VERSION
const char info::PROJECT_VERSION[] = ""
Definition at line 11 of file config.h.
Referenced by info_project_version().