bulk: utils Namespace Reference
utils Namespace Reference
Classes
class defer
defer wrapper
struct overload
Functions
template<class... Ts>
overload (Ts...) -> overload< Ts... >
with std::string
std::string & ltrim (std::string &str, std::string const &whitespace=" \r\n\t\v\f")
std::string & rtrim (std::string &str, std::string const &whitespace=" \r\n\t\v\f")
std::string & trim (std::string &str, std::string const &whitespace=" \r\n\t\v\f")
std::string & to_lower (std::string &str)
std::string & to_upper (std::string &str)
with std::string_view
std::string_view ltrim (std::string_view str, std::string_view whitespace=" \r\n\t\v\f")
std::string_view rtrim (std::string_view str, std::string_view whitespace=" \r\n\t\v\f")
std::string_view trim (std::string_view str, std::string_view whitespace=" \r\n\t\v\f")
Function Documentation
ltrim() [1/2]
std::string & utils::ltrim (std::string & str, std::string const & whitespace = " \r\n\t\v\f") inline
Definition at line 21 of file string_utils.hpp.
{
  str.erase(0, str.find_first_not_of(whitespace));
  return str;
}
Referenced by trim(), and trim().
ltrim() [2/2]
std::string_view utils::ltrim (std::string_view str, std::string_view whitespace = " \r\n\t\v\f") inline
Definition at line 48 of file string_utils.hpp.
{
  auto const pos(str.find_first_not_of(whitespace));
  str.remove_prefix(std::min(pos, str.length()));
  return str;
}
overload()
template<class... Ts> utils::overload (Ts...) -> overload< Ts... >
rtrim() [1/2]
std::string & utils::rtrim (std::string & str, std::string const & whitespace = " \r\n\t\v\f") inline
Definition at line 26 of file string_utils.hpp.
{
  str.erase(str.find_last_not_of(whitespace) + 1);
  return str;
}
Referenced by trim(), and trim().
rtrim() [2/2]
std::string_view utils::rtrim (std::string_view str, std::string_view whitespace = " \r\n\t\v\f") inline
Definition at line 54 of file string_utils.hpp.
{
  auto const pos(str.find_last_not_of(whitespace));
  str.remove_suffix(std::min(str.length() - pos - 1, str.length()));
  return str;
}
to_lower()
std::string & utils::to_lower (std::string & str) inline
Definition at line 35 of file string_utils.hpp.
{
  std::transform(str.cbegin(), str.cend(), str.begin(), ::tolower);
  return str;
}
to_upper()
std::string & utils::to_upper (std::string & str) inline
Definition at line 40 of file string_utils.hpp.
{
  std::transform(str.cbegin(), str.cend(), str.begin(), ::toupper);
  return str;
}
trim() [1/2]
std::string & utils::trim (std::string & str, std::string const & whitespace = " \r\n\t\v\f") inline
Definition at line 31 of file string_utils.hpp.
{
  return rtrim(ltrim(str, whitespace), whitespace);
}
References ltrim(), and rtrim().
Referenced by cmd::provider::ConsoleParser::advance().
trim() [2/2]
std::string_view utils::trim (std::string_view str, std::string_view whitespace = " \r\n\t\v\f") inline
Definition at line 60 of file string_utils.hpp.
{
  return rtrim(ltrim(str, whitespace), whitespace);
}
References ltrim(), and rtrim().