bulk: src/utils/str_utils.hpp File Reference
str_utils.hpp File Reference
#include <algorithm>
#include <string>
#include <string_view>
Functions
with std::string
std::string & ltrim (std::string &str, std::string const &whitespace=" \r\n\t\v\f")
std::string & rtrim (std::string &str, std::string const &whitespace=" \r\n\t\v\f")
std::string & trim (std::string &str, std::string const &whitespace=" \r\n\t\v\f")
std::string & to_lower (std::string &str)
std::string & to_upper (std::string &str)
with std::string_view
std::string_view ltrim (std::string_view str, std::string const &whitespace=" \r\n\t\v\f")
std::string_view rtrim (std::string_view str, std::string const &whitespace=" \r\n\t\v\f")
std::string_view trim (std::string_view str, std::string const &whitespace=" \r\n\t\v\f")
Function Documentation
ltrim() [1/2]
std::string & ltrim (std::string & str, std::string const & whitespace = " \r\n\t\v\f")
Definition at line 19 of file str_utils.hpp.
{
  str.erase(0, str.find_first_not_of(whitespace));
  return str;
}
Referenced by trim(), and trim().
ltrim() [2/2]
std::string_view ltrim (std::string_view str, std::string const & whitespace = " \r\n\t\v\f")
Definition at line 46 of file str_utils.hpp.
{
  const auto pos(str.find_first_not_of(whitespace));
  str.remove_prefix(std::min(pos, str.length()));
  return str;
}
rtrim() [1/2]
std::string & rtrim (std::string & str, std::string const & whitespace = " \r\n\t\v\f")
Definition at line 24 of file str_utils.hpp.
{
  str.erase(str.find_last_not_of(whitespace) + 1);
  return str;
}
Referenced by trim(), and trim().
rtrim() [2/2]
std::string_view rtrim (std::string_view str, std::string const & whitespace = " \r\n\t\v\f")
Definition at line 52 of file str_utils.hpp.
{
  const auto pos(str.find_last_not_of(whitespace));
  str.remove_suffix(std::min(str.length() - pos - 1, str.length()));
  return str;
}
to_lower()
std::string & to_lower (std::string & str)
Definition at line 33 of file str_utils.hpp.
{
  std::transform(str.cbegin(), str.cend(), str.begin(), ::tolower);
  return str;
}
Referenced by cmd::provider::InputStreamParser::advance().
to_upper()
std::string & to_upper (std::string & str)
Definition at line 38 of file str_utils.hpp.
{
  std::transform(str.cbegin(), str.cend(), str.begin(), ::toupper);
  return str;
}
trim() [1/2]
std::string & trim (std::string & str, std::string const & whitespace = " \r\n\t\v\f")
Definition at line 29 of file str_utils.hpp.
{
  return ltrim(rtrim(str, whitespace), whitespace);
}
References ltrim(), and rtrim().
Referenced by cmd::provider::InputStreamParser::advance().
trim() [2/2]
std::string_view trim (std::string_view str, std::string const & whitespace = " \r\n\t\v\f")
Definition at line 58 of file str_utils.hpp.
{
  return ltrim(rtrim(str, whitespace), whitespace);
}
References ltrim(), and rtrim().